### ISSUE TITLE
unable to choose activities

### ISSUE THREAD

**Issue by iv-enovation** [a-camacho/scgr#1]
when a user is a member of one group, it seems not possible to choose activities to compare, the list is empty

the warning is shown: Notice: Undefined offset: 0 in /var/www/ticket/moodle341/grade/report/scgr/views/student.php on line 13
in both "me vs others" and "my group vs other groups"

**Comment by a-camacho** [comment]
Hi,

I tried to reproduce the error, but could not have the same environment as you.
For the course you are talking about : 

- Are there multiple groups with members ?
- Does your users have special permissions ? (this plugin was made for students, and ignores others roles, so if your students have a special permission in the course - teacher or nonediting teacher - they will be ignored).

I'm trying to understand why the variable is empty.

**Comment by iv-enovation** [comment]
Hi, 

Answering your questions:
- there are 2 groups that both have 2 members
- users are students

The reported issue happens to students that are members of the group that is the first in the list of groups. In stripTutorsGroupFromGroupIDS() that is hardcoded in $groups_to_ignore = array(1);

But still, a user from the 2nd group does not see activities in the list, although the error is gone. In the course i have 3 assignments with all submissions graded for all students. I attached the course backup
[backup-moodle2-course-2-c1-20180525-1519.mb.gz](https://github.com/a-camacho/scgr/files/2039682/backup-moodle2-course-2-c1-20180525-1519.mb.gz)


Ivan

**Comment by a-camacho** [comment]
Hello,
I can fix the problem really soon but I am having trouble setting up the same environment that you have, so I can modify the plugin and better understand the source of problem.
If you could give me access to the plugin directory, and an user account to access the problem on your environment, it would be really easy. If not (what I perfectly understand, as you maybe don’t have a test environment) I will try to set up a test environment at work ASAP.
Thanks for your feedback, and hope to be able to solve your issue soon.
Best regards, André Camacho

On Fri, May 25, 2018 at 16:25, iv-enovation <notifications@github.com> wrote:
Hi,

Answering your questions:

 * there are 2 groups that both have 2 members
 * users are students

The reported issue happens to students that are members of the group that is the first in the list of groups. In stripTutorsGroupFromGroupIDS() that is hardcoded in $groups_to_ignore = array(1);

But still, a user from the 2nd group does not see activities in the list, although the error is gone. In the course i have 3 assignments with all submissions graded for all students. I attached the course backup
backup-moodle2-course-2-c1-20180525-1519.mb.gz [https://github.com/a-camacho/scgr/files/2039682/backup-moodle2-course-2-c1-20180525-1519.mb.gz]

Ivan

**Comment by iv-enovation** [comment]
Hi Andre, 

Sorry access to my test installation is not possible. To replicate the issue it might be enough if you create a new fresh Moodle instance, add one course, and set up users within the course

Best regards,
Ivan

**Comment by a-camacho** [comment]
Hi Ivan,

This issue should be fixed in milestone 1.0.
I will release version 1.0 of plugin these next few days.
Hope it will finally work as you expect.

Best regards,
André

**Comment by a-camacho** [comment]
Hi,

Sorry for this reply that is very delayed, but I wanted to notify to you that we made some changes to the plugin.
I think your issue(s) should be fixed now.

Best regards,
André Camacho
