### ISSUE TITLE
errors when configuring report as admin

### ISSUE THREAD

**Issue by iv-enovation** [a-camacho/scgr#2]
as an admin, when i go to a course -> gradebook setup -> Social comparison report following is displayed:

Notice: Trying to get property of non-object in /var/www/ticket/moodle341/grade/report/scgr/index.php on line 140

Notice: Trying to get property of non-object in /var/www/ticket/moodle341/grade/report/scgr/index.php on line 151

Notice: Trying to get property of non-object in /var/www/ticket/moodle341/grade/report/scgr/index.php on line 162

Notice: Trying to get property of non-object in /var/www/ticket/moodle341/grade/report/scgr/index.php on line 163
error : user role error

**Comment by a-camacho** [comment]
I'm actually working on this issue (and the other ones). I hope to be able to tag a new release version during these two weeks.
